namespace: "community.ansible"

name: "ibm"

version: "1.0.0"

readme: "README.md"

authors:

    - "Umar Ali"

description: "Ansible modules collection for IBM-Cloud."

license:

    - "MPL-2.0"

issues: https://github.com/marifse/ community.ansible.ibm.cloud/issues

homepage: https://github.com/marifse/ community.ansible.ibm.cloud

tags:

    - ibmcloud

    - cloud

    - collection

    - ansible

repository: https://github.com/marifse/ community.ansible.ibm.cloud

